channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - azureml-mlflow==1.56.0
      - azure-ai-ml==1.0.0
      - pyarrow==10.0.0
      - pandas==1.2.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - matplotlib
      - azureml-defaults==1.56.0.post1
      - 'inference-schema[numpy-support]==1.7'
      - joblib==1.2.0
      - >-
        git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - >-
        git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
